export type ImportHeaderCreateInput = {
  action?: string | null;
  b1DeclaSub1?: string | null;
  b20DelivTermsSub1?: string | null;
  b20DelivTermsSub2?: string | null;
  b20DelivTermsSub3?: string | null;
  b22CurrencyCode?: string | null;
  b22TotalAmount?: number | null;
  b25BorderTrans?: number | null;
  b26InlandTrans?: number | null;
  b27PlaceOfLoading?: string | null;
  b48DeferredPay?: number | null;
  b5Items?: number | null;
  b9TotalFreight?: number | null;
  b9TotalInsurance?: number | null;
  box47CdPayMethod?: string | null;
  boxaOfficeCode?: string | null;
  boxaOfficeSubCode?: string | null;
  cdGuaranteeMethod?: string | null;
  direction?: string | null;
  information?: string | null;
  moduleField?: string | null;
  userId?: string | null;
};
